spring.application.name=wheelchairhelper
server.port=${PORT:8080}
spring.profiles.active=local

#Supabase Configuration
supabase.url=https://esqtzwvhfwcisidtloaf.supabase.co

#Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wheelchair.helper.bklk@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORS Configuration (fï¿½r Vercel Frontend)
cors.allowed-origins=http://localhost:3000,https://your-app.vercel.app